### ISSUE TITLE
Item rendering bug

### ISSUE THREAD

**Issue by dangerousones** [Noach05/HARDIS#4]
**Describe the bug**
When a HARDIS mod item is shown in the inventory or hotbar, it's model extends out of the bounds and into adjacent spots
**To Reproduce**
1. Open inventory / JEI / container
2. Go to HARDIS item
3. Observe

**Expected behavior**
Items should not be rendering out of their boxes.
**Screenshots**

**Additional context**

**Comment by Noach05** [comment]
Screenshots where? xD

**Comment by dangerousones** [comment]
I don't have any, but just open the creative menu and it's evident
